# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
sudo: required
bioc_required: true
  
before_install:
 - curl -OL http://raw.githubusercontent.com/eddelbuettel/r-travis/master/scripts/travis-tool.sh
 - chmod 755 ./travis-tool.sh
 - ./travis-tool.sh bootstrap
  
install:
 #- ./travis-tool.sh install_deps
 #- ./travis-tool.sh install_bioc_deps
 - ./travis-tool.sh install_aptget r-cran-rcpp g++-4.9
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
  
notifications:
  email:
    on_success: change
    on_failure: change
  
env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual --no-resave-data"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"

