# Sample .travis.yml for R projects.
#
# See https://github.com/craigcitro/r-travis
#     https://github.com/eddelbuettel/r-travis/

language: c

# Opt into fully virtualized infrastructure
# cf http://blog.travis-ci.com/2015-03-31-docker-default-on-the-way/
sudo: required
  
before_install:
  - curl -OL https://raw.githubusercontent.com/alexg9010/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  
install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_bioc_deps
  - ./travis-tool.sh install_aptget r-cran-rcpp g++-4.9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
  
script:
  - ./travis-tool.sh run_tests

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - CXX="g++-4.8"
    - CC="gcc-4.8"